### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by alxwrd** [ratlog/ratlog.github.io#8]
hello 👋 !

From the README:

> We always welcome new developers to contribute new tooling to the Ratlog ecosystem. If you would like to create or extend a logging library in a programming language of your choice ...

I would be interested in implementing a Python version but just had a couple of questions:

1. Is it prefered that the overall style of a repo mimics that of ratlog.js? e.g.
    > ![image](https://user-images.githubusercontent.com/13941027/39122479-f6fd1cf4-46ec-11e8-9e3c-dad0df8b8566.png)
2. Is there a desire that _when_/_if_ a project reaches a certain level, it would be transferred to the Ratlog organisation?

**Comment by jorinvo** [comment]
hi @alxwrd, that's awesome!

I think that libraries should fit the ecosystem and style of each language. So you should do what you think is the best way to do things in Python. Maybe you can take inspiration from other popular loggers already existing in Python and so on. 
It is also fine if you like to provide more features than the JS library or if you simple extend an existing Python logging library.
I think that the JS version is a good place to get started. You can see how things are implemented there and copy some documentation. Also have a look at how it's using the JSON spec for testing. That way you don't have to write tests yourself.

If you like, we can definitely add the Python logger to the ratlog organization. That's exactly what I created the organization for.

Let me know, if I can help with anything! We can still adapt the spec in case anything is not specific enough or misleading.

**Comment by alxwrd** [comment]
Fantastic! I'll make a start soon and keep you updated if I run into issues with the spec.

**Comment by alxwrd** [comment]
hi @jorinvo !

I've come across a potential inconsistency with the testsuite. In the following test, the fields aren't alphabetically sorted, while the rest are.

```json
{
  "log": "counting event | event: one | count: 1\n",
  "data": {
    "message": "counting event",
    "fields": {
      "event": "one",
      "count": "1"
    }
  }
}
```

I have opted to sort fields alphabetically as Python dictionaries/hashmaps are [not guaranteed to preserve order](https://docs.python.org/2/library/stdtypes.html#dict.items).

I will open a PR with these values swapped for discussion :thinking:

**Comment by jorinvo** [comment]
Closing this for now since it's not a specific issue anymore.
Feel free to open a new issue if something comes up :)
